

#if defined (DD_DISABLE_PARAM_ENCODEING)

  #define DD_COLOR_red            "red"
  #define DD_COLOR_green          "green"
  #define DD_COLOR_blue           "blue"
  #define DD_COLOR_yellow         "yellow"
  #define DD_COLOR_magenta        "magenta"
  #define DD_COLOR_cyan           "cyan"
  #define DD_COLOR_white          "white"
  #define DD_COLOR_black          "black"
  #define DD_COLOR_orange         "orange"
  #define DD_COLOR_pink           "pink"
  #define DD_COLOR_gray           "gray"
  #define DD_COLOR_darkgray       "darkgray"
  #define DD_COLOR_lightgray      "lightgray"
  #define DD_COLOR_brown          "brown"
  #define DD_COLOR_purple         "purple"
  #define DD_COLOR_darkgreen      "darkgreen"
  #define DD_COLOR_darkblue       "darkblue"
  #define DD_COLOR_indigo         "indigo"
  #define DD_COLOR_lightgreen     "lightgreen"
  #define DD_COLOR_darkred        "darkred"
  #define DD_COLOR_lightblue      "lightblue"

  #define DD_COLOR_azure          "azure"
  #define DD_COLOR_plum           "plum"
  #define DD_COLOR_gold           "gold"
  #define DD_COLOR_teal           "teal"
  #define DD_COLOR_ivory          "ivory"
  #define DD_COLOR_coral          "coral"
  #define DD_COLOR_beige          "beige"
  #define DD_COLOR_snow           "snow"
  #define DD_COLOR_aqua           "aqua"
  #define DD_COLOR_lemonchiffon   "lemonchiffon"
  #define DD_COLOR_navy           "navy"
  #define DD_COLOR_midnightblue   "midnightblue"
  #define DD_COLOR_aliceblue      "aliceblue"

#else

  #define DD_COLOR_red            "@a"
  #define DD_COLOR_green          "@b"
  #define DD_COLOR_blue           "@c"
  #define DD_COLOR_yellow         "@d"
  #define DD_COLOR_magenta        "@e"
  #define DD_COLOR_cyan           "@f"
  #define DD_COLOR_white          "@g"
  #define DD_COLOR_black          "@h"
  #define DD_COLOR_orange         "@i"
  #define DD_COLOR_pink           "@j"
  #define DD_COLOR_gray           "@k"
  #define DD_COLOR_darkgray       "@l"
  #define DD_COLOR_lightgray      "@m"
  #define DD_COLOR_brown          "@n"
  #define DD_COLOR_purple         "@o"
  #define DD_COLOR_darkgreen      "@p"
  #define DD_COLOR_darkblue       "@q"
  #define DD_COLOR_indigo         "@r"
  #define DD_COLOR_lightgreen     "@s"
  #define DD_COLOR_darkred        "@t"
  #define DD_COLOR_lightblue      "@u"

  #define DD_COLOR_azure          "@A"
  #define DD_COLOR_plum           "@B"
  #define DD_COLOR_gold           "@C"
  #define DD_COLOR_teal           "@D"
  #define DD_COLOR_ivory          "@E"
  #define DD_COLOR_coral          "@F"
  #define DD_COLOR_beige          "@G"
  #define DD_COLOR_snow           "@H"
  #define DD_COLOR_aqua           "@I"
  #define DD_COLOR_lemonchiffon   "@J"
  #define DD_COLOR_navy           "@K"
  #define DD_COLOR_midnightblue   "@L"
  #define DD_COLOR_aliceblue      "@M"


#endif