

#if defined (DD_DISABLE_PARAM_ENCODING)

  #define DD_COLOR_red            "red"
  #define DD_COLOR_green          "green"
  #define DD_COLOR_blue           "blue"
  #define DD_COLOR_yellow         "yellow"
  #define DD_COLOR_magenta        "magenta"
  #define DD_COLOR_cyan           "cyan"
  #define DD_COLOR_white          "white"
  #define DD_COLOR_black          "black"
  #define DD_COLOR_orange         "orange"
  #define DD_COLOR_pink           "pink"
  #define DD_COLOR_gray           "gray"
  #define DD_COLOR_darkgray       "darkgray"
  #define DD_COLOR_lightgray      "lightgray"
  #define DD_COLOR_brown          "brown"
  #define DD_COLOR_purple         "purple"
  #define DD_COLOR_darkgreen      "darkgreen"
  #define DD_COLOR_darkblue       "darkblue"
  #define DD_COLOR_indigo         "indigo"
  #define DD_COLOR_lightgreen     "lightgreen"
  #define DD_COLOR_darkred        "darkred"
  #define DD_COLOR_lightblue      "lightblue"
  #define DD_COLOR_darkorange     "darkorange"
  #define DD_COLOR_darkviolet     "darkviolet"
  #define DD_COLOR_violet         "violet"
  #define DD_COLOR_lightcyan      "lightcyan"

  #define DD_COLOR_azure          "azure"
  #define DD_COLOR_plum           "plum"
  #define DD_COLOR_gold           "gold"
  #define DD_COLOR_teal           "teal"
  #define DD_COLOR_ivory          "ivory"
  #define DD_COLOR_coral          "coral"
  #define DD_COLOR_beige          "beige"
  #define DD_COLOR_snow           "snow"
  #define DD_COLOR_aqua           "aqua"
  #define DD_COLOR_lemonchiffon   "lemonchiffon"
  #define DD_COLOR_navy           "navy"
  #define DD_COLOR_midnightblue   "midnightblue"
  #define DD_COLOR_aliceblue      "aliceblue"
  #define DD_COLOR_antiquewhite   "antiquewhite"
  #define DD_COLOR_bisque         "bisque"
  #define DD_COLOR_cornsilk       "cornsilk"
  #define DD_COLOR_crimson        "crimson"
  #define DD_COLOR_maroon         "maroon"
  #define DD_COLOR_olive          "olive"
  #define DD_COLOR_orchid         "orchid"
  #define DD_COLOR_salmon         "salmon"
  #define DD_COLOR_silver         "silver"
  #define DD_COLOR_skyblue        "skyblue"
  #define DD_COLOR_tomato         "tomato"
  #define DD_COLOR_turquoise      "turquoise"
  #define DD_COLOR_wheat          "wheat"
  #define DD_COLOR_whitesmoke     "whitesmoke"
  #define DD_COLOR_tan            "tan"
  #define DD_COLOR_springgreen    "springgreen"
  #define DD_COLOR_steelblue      "steelblue"
  #define DD_COLOR_slategray      "slategray"
  #define DD_COLOR_slateblue      "slateblue"
  #define DD_COLOR_seashell       "seashell"
  #define DD_COLOR_royalblue      "royalblue"
  #define DD_COLOR_rosybrown      "rosybrown"
  #define DD_COLOR_peru           "peru"
  #define DD_COLOR_chartreuse     "chartreuse"
  #define DD_COLOR_chocolate      "chocolate"
  #define DD_COLOR_greenyellow    "greenyellow"
  #define DD_COLOR_honeydew       "honeydew"
  #define DD_COLOR_hotpink        "hotpink"
  #define DD_COLOR_indianred      "indianred"
  #define DD_COLOR_khaki          "khaki"
  #define DD_COLOR_lavender       "lavender"

#else

  #define DD_COLOR_red            "@a"
  #define DD_COLOR_green          "@b"
  #define DD_COLOR_blue           "@c"
  #define DD_COLOR_yellow         "@d"
  #define DD_COLOR_magenta        "@e"
  #define DD_COLOR_cyan           "@f"
  #define DD_COLOR_white          "@g"
  #define DD_COLOR_black          "@h"
  #define DD_COLOR_orange         "@i"
  #define DD_COLOR_pink           "@j"
  #define DD_COLOR_gray           "@k"
  #define DD_COLOR_darkgray       "@l"
  #define DD_COLOR_lightgray      "@m"
  #define DD_COLOR_brown          "@n"
  #define DD_COLOR_purple         "@o"
  #define DD_COLOR_darkgreen      "@p"
  #define DD_COLOR_darkblue       "@q"
  #define DD_COLOR_indigo         "@r"
  #define DD_COLOR_lightgreen     "@s"
  #define DD_COLOR_darkred        "@t"
  #define DD_COLOR_lightblue      "@u"
  //#define DD_COLOR_darkorange     "@v"
  //#define DD_COLOR_darkviolet     "@w"
  #define DD_COLOR_violet         "@x"
  #define DD_COLOR_lightcyan      "@y"
  #define DD_COLOR_darkviolet     "@aa"
  #define DD_COLOR_darkorange     "@ab"

  #define DD_COLOR_azure          "@A"
  //#define DD_COLOR_plum           "@B"
  #define DD_COLOR_gold           "@C"
  //#define DD_COLOR_teal           "@D"
  #define DD_COLOR_ivory          "@E"
  #define DD_COLOR_coral          "@F"
  //#define DD_COLOR_beige          "@G"
  #define DD_COLOR_snow           "@H"
  #define DD_COLOR_aqua           "@I"
//  #define DD_COLOR_lemonchiffon   "@J"
  #define DD_COLOR_navy           "@K"
//  #define DD_COLOR_midnightblue   "@L"
  // #define DD_COLOR_aliceblue      "@M"
  // #define DD_COLOR_antiquewhite   "@N"
  //#define DD_COLOR_bisque         "@O"
  //#define DD_COLOR_cornsilk       "@P"
  // #define DD_COLOR_crimson        "@Q"
  // #define DD_COLOR_maroon         "@R"
  #define DD_COLOR_olive          "@S"
  // #define DD_COLOR_orchid         "@T"
  // #define DD_COLOR_salmon         "@U"
  #define DD_COLOR_silver         "@V"
  #define DD_COLOR_skyblue        "@W"
 // #define DD_COLOR_tomato         "@X"
  //#define DD_COLOR_turquoise      "@Y"
  //#define DD_COLOR_wheat          "@Z"
  #define DD_COLOR_whitesmoke     "@AA"
  #define DD_COLOR_tan            "@AB"
  #define DD_COLOR_springgreen    "@AC"
  #define DD_COLOR_steelblue      "@AD"
  #define DD_COLOR_slategray      "@AE"
  #define DD_COLOR_slateblue      "@AF"
  #define DD_COLOR_seashell       "@AG"
  #define DD_COLOR_royalblue      "@AH"
  #define DD_COLOR_rosybrown      "@AI"
  #define DD_COLOR_peru           "@AJ"
  #define DD_COLOR_chartreuse     "@AK"
  #define DD_COLOR_chocolate      "@AL"
  #define DD_COLOR_greenyellow    "@AM"
  #define DD_COLOR_honeydew       "@AN"
  #define DD_COLOR_hotpink        "@AO"
  #define DD_COLOR_indianred      "@AP"
  #define DD_COLOR_khaki          "@AQ"
  #define DD_COLOR_lavender       "@AR"
  #define DD_COLOR_lemonchiffon   "@AS"
  #define DD_COLOR_midnightblue   "@AT"
  #define DD_COLOR_aliceblue      "@AU"
  #define DD_COLOR_antiquewhite   "@AV"
  #define DD_COLOR_cornsilk       "@AW"
  #define DD_COLOR_turquoise      "@AX"
  #define DD_COLOR_bisque         "@AY"
  #define DD_COLOR_beige          "@AZ"
  #define DD_COLOR_teal           "@BA"
  #define DD_COLOR_crimson        "@BB"
  #define DD_COLOR_maroon         "@BC"
  #define DD_COLOR_orchid         "@BD"
  #define DD_COLOR_salmon         "@BE"
  #define DD_COLOR_wheat          "@BF"
  #define DD_COLOR_plum           "@BG"
  #define DD_COLOR_tomato         "@BH"


#endif