#define C_TONE             "#00"
#define C_CAPTURE          "#01"
#define C_RECC             "#02"
#define C_SAVEC            "#03"
#define C_PLAYC            "#04"
#define C_KAL              "#05"
#define C_SAVEIMG          "#06"
#define C_CACHEIMG         "#07"
#define C_SAVEPIXIMG       "#08"
#define C_CACHEPIXIMG      "#09"
#define C_SAVEPIXIMG16     "#0a"
#define C_CACHEPIXIMG16    "#0b"
#define C_SAVEPIXIMGGS     "#0c"
#define C_CACHEPIXIMGGS    "#0d"
#define C_NOTONE           "#0e"
// will reserver #fn if after 0f
#define C_PLAYSND          "#f0"
#define C_STOPSND          "#f1"
#define C_SAVESND          "#f2"
#define C_CACHESND         "#f3"
#define C_STREAMSND        "#f4"
#define C_SAVECACHEDIMG    "#f5"
#define C_SAVECACHEDIMGS   "#f6"
#define C_ALERT            "#f7"

#define C_border           "#10"
#define C_padding          "#11" 
#define C_bgcolor          "#12"
#define C_nobgcolor        "#13"
#define C_feedback         "#14"
#define C_clear            "#15"
#define C_flash	           "#16"
#define C_flasharea        "#17"
#define C_visible          "#18"
#define C_opacity          "#19"
#define C_transparent      "#20"
#define C_alpha            "#21"
#define C_margin           "#22" 
#define C_disabled         "#23"
#define C_blend            "#25"
#define C_noblend          "#26"
#define C_explicitfeedback "#27"
#define C_pushlevel        "#28"
#define C_poplevel         "#29"
#define C_switchlevel      "#2a"
#define C_dellevel         "#2b"
#define C_reordlevel       "#2c"
#define C_levelopacity     "#2d"
#define C_leveltransparent "#2e"
#define C_addlevel         "#2f"


#define C_fillscreen       "#30"
#define C_drawtriangle     "#31"
#define C_drawline         "#32"
#define c_drawrect         "#33"
#define C_drawcircle       "#34"
#define C_shownumber       "#35"
#define C_resetsegoffcolor "#36"
#define C_ledon            "#37"
#define C_ledoff           "#38"
#define C_writeline        "#39"

#define C_setlevelanchor    "#3a"
#define C_movelevelanchorby "#3b"
#define C_reglevelbg        "#3c"
#define C_setlevelbg        "#3d"
#define C_setlevelnobg      "#3e"
#define C_addtoplevel       "#3f"


#define C_textcolor        "#40"
#define C_textsize         "#41"
#define C_drawstr          "#42"
#define C_crect            "#43"
#define C_rect             "#44"
#define C_ccircle          "#45"
#define C_circle           "#46"
#define C_ledoncolor       "#47"
#define C_ledoffcolor      "#48"
#define C_pencolor         "#49"

#define C_anilevelbg       "#4a"
#define C_stopanilevelbg   "#4b"
#define C_explevelsasimg   "#4c"
#define C_explevelasregbg  "#4d"

#define C_drawtextline     "#4f"


#define C_print            "#50"
#define C_textfont         "#51"
#define C_drawroundrect    "#52"
#define C_drawpixel        "#53"
#define C_drawchar         "#54"
#define C_println          "#55"
#define C_showformatted    "#56"
#define C_showhex          "#57"
#define C_bitwise          "#58"
#define C_ledtoggle        "#59"
#define C_bitbybit         "#5a"
#define C_autoscroll       "#60"
#define C_display          "#61"
#define C_scrollleft       "#62"
#define C_scrollright      "#63"
#define C_pixelcolor       "#64"
#define C_bgpixelcolor     "#65"
#define C_setcursor        "#66"
#define C_movecursorby     "#67"
#define C_settextwrap      "#68"
#define C_drawtext         "#69"
#define C_text             "#6a"
#define C_select           "#6b"
#define C_deselect         "#6c"
#define C_highlighborder   "#6d"
#define C_unselectedtext   "#6e"
#define C_write            "#70"	
#define C_cpoly            "#71"
#define C_cpolyin          "#72"
#define C_poly             "#73"
#define C_trisas           "#74"
#define C_coval            "#75"
#define C_oval             "#76"
#define C_dot              "#77"
#define C_ptextfont        "#78"
#define C_ptextsize        "#79"
#define C_add              "#7a"
#define C_remove           "#7b"
#define C_offset           "#7c"
#define C_ledhoribar       "#80"
#define C_ledvertbar       "#81"
#define C_home             "#82"
#define C_seth             "#83"
#define C_pensize          "#84"
#define C_fillcolor        "#85"
#define C_nofillcolor      "#86"
#define C_segcolor	       "#87"
#define C_segon            "#88"
#define C_segoff           "#89"	
#define C_setsegon         "#90"
#define C_label            "#91"
#define C_cursor           "#92"
#define C_ledhoribarex     "#93"
#define C_ledvertbarex     "#94"
#define C_ledonex          "#95"
#define C_loadimagefile    "#96"
//#define C_unloadimagefile  "#97"
#define C_drawimagefile    "#98"
#define C_drawimagefilefit "#99"

#define C_goto                 "#a0"
#define C_zoomto               "#a1"
#define C_zoom                 "#a2"
#define C_showdigit            "#a4"
#define C_setrot               "#a5"
//#define C_loadimagefilecropped "#a6"
#define C_carc                 "#a7"
#define C_arc                  "#a8"
#define c_drawoval             "#a9"
#define c_drawarc              "#aa"

#define C_autorecenter     "#ab"
#define C_colors           "#ac"
#define C_movetocenter     "#ad"
#define C_movetopos        "#ae" 
#define C_snappy           "#af" 

#define C_valuerange       "#b0" 
#define C_showvalue        "#b1" 

#define C_loadurl          "#ba"
#define C_loadhtml         "#bb"
#define C_execjs           "#bc"

#define C_connect          "#bd"
#define C_disconnect       "#be"

#define C_fd               "fd"
#define C_bk               "bk"
#define C_lt               "lt"
#define C_rt               "rt"

#define C_loadimagefilecropped "#a6"
#define C_unloadimagefile      "#97"
#define C_unloadallimagefiles  "#9a"

#define C_bgimg            "#9b"
#define C_nobgimg          "#9c"
#define C_explayerasbgimg  "#9d"
#define C_anibgimg         "#9e"
#define C_stopanibgimg     "#9f"




